# Generated by Django 5.1 on 2024-11-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_jobposting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_handyman",
            field=models.IntegerField(default=-1),
        ),
    ]
