# Generated by Django 5.1.2 on 2024-11-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_reviews_user_user_reviews_review_workhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposting",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobposting",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
