# Generated by Django 5.1.2 on 2024-11-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_jobposting_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, default='General', max_length=60),
        ),
    ]
